### ISSUE TITLE
Data Files for Events and News

### ISSUE THREAD

**Issue by TangoYankee** [TravisSpark/spark-website#14]
# Overview
The task of displaying events should be separated into two separate files. The markdown file in _pages folder will serve as a template for the display of the information. A yaml file created in the _data folder will serve the value of each article to the markdown file. 

Repeat this file structure for news.

## To-Do List
- [ ] Create two yaml files within _data folder
       1. events.yml
       2. news.yml
- [ ] Select variables for each file.
     - Make sure that these are variables will serve the needs of every entry into that file
- [ ] Input initial values into each file
     - This will serve as a model for future edits.

## Reference
-  In [jekyll-github-demo](https://github.com/TangoYankee/jekyll-github-demo), [education.yml](https://github.com/TangoYankee/jekyll-github-demo/blob/gh-pages/_data/education.yml) serves [education.md](https://github.com/TangoYankee/jekyll-github-demo/blob/gh-pages/_pages/education.md)
- [Yaml Liquid Markdown Tutorial](https://idratherbewriting.com/documentation-theme-jekyll/mydoc_yaml_tutorial)
- [Jekyll Front Matter](https://jekyllrb.com/docs/frontmatter/)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)

### Note
-  yaml files are very picking about their formatting. If you're getting an error, make sure to check your formatting first.
